application: tool-save-url
version: v1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|txt|ico))$
  static_files: _cdn/\1
  upload: _cdn/.*\.(gif|png|jpg|txt)$

- url: /_cdn
  static_dir: _cdn

- url: /.*
  script: app.APP

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^_cdn/sass/(.*/)*.*$
- ^_cdn/css/app.css.map


