application: sun-backends
version: h2
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /_ah/spi/.*
  script: app.eapis.ENDPOINTS_API_SERVER

- url: /.*
  script: app.APP


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

